### ISSUE TITLE
Wizards Doom 

### ISSUE THREAD

**Issue by Nikusiswrld** [js-dos/dos.zone.db#4]
Wizard's Doom is a timed action strategy game with gameplay similar to Soko-Ban. The evil Wizard Chang Li Xung has imprisoned You in a deep dungeon named the Maze of Keys. Escaping from each of 50 levels requires pushing the movable directional (left, right, up, down, all ways) blocks through the walls in order to crush the bricks and get access to all 5 Keys of Power. After collecting 5 rusted keys a Magic Key will appear, allowing to pass next level passage doors. All of this within just 99 seconds. The points are awarded for crushing wall bricks, collecting keys and completing levels. Each completed level is awarded with one extra life.

--
** DO NOT REMOVE **
`./build/dz.js dc update --key dos/final-doom --locale en`

**Comment by caiiiycuk** [comment]
Fixed, thank you.
